fork_me_ribbon_url: https://github.com/coderefinery/instructor_training
baseurl: "/instructor_training"
title: "CodeRefinery for contributors and instructors"

# where things are
source: .
destination: ./_site
layouts_dir: ./jekyll-common/layouts
includes_dir: ./jekyll-common/includes

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: ['jekyll-common/pages']

collections:
  episodes:
    output: true
    permalink: /:name/
